const wordsString = "elephant,frog,giraffe,helicopter,igloo,jungle,kangaroo,lion,monkey,ninja,ocean,penguin,queen,robot,sun,tiger,umbrella,volcano,watermelon,xylophone,yacht,zebra,astronaut,butterfly,computer,dinosaur,eagle,firefighter,guitar,hamburger,island,jellyfish,kite,lighthouse,mountain,notebook,octopus,pizza,quilt,rainbow,spider,telescope,unicorn,vampire,wizard,x-ray,yo-yo,zipper,airplane,bicycle,camera,diamond,envelope,flower,glasses,house,ice cream,jacket,key,leaf,moon,nest,owl,pencil,rocket,star,tree,violin,watch,bear,car,desk,egg,fish,goat,hat,ice,juice,king,lamp,mouse,nut,orange,pig,ring,shoe,train,vase,window,yam,zoo,ant,bird,cow,duck,eye,fox,gold,hand,iron,jar,leg,milk,nose,oven,pear,rose,ship,tent,van,web,bat,cup,ear,fly,gum,ink,jam,lip,map,net,oak,pen,rat,toe,wax,zip,arm,bus,dot,fan,gas,hut,jaw,keg,log,mat,pan,rug,sea,tea,urn,vet,wig,yak,art,boy,day,fog,guy,hay,inn,job,kid,law,man,now,oil,pie,row,sky,toy,use,vow,way,yes,act,bad,dry,eat,fat,gap,hit,joy,let,mud,new,own,pot,red,sad,tin,war,yet,age,bag,cab,end,fix,box,kit,lid,mix,nod,off,pop,rub,saw,tax,you,air,bed,cap,fun,get,hot,ill,jet,kin,out,run,top,win,yep,add,bug,did,got,one,ten,old,pet,ambulance,anchor,archery,backpack,bacon,badge,balloon,sandwich,castle,candle,cannon,carriage,cave,cheese,cherry,church,clock,cloud,coffee,comb,compass,corn,crab,crown,cupcake,darts,dice,dolphin,donut,drum,earth,fence,finger,fire,flag,fork,frog,ghost,glove,grapes,grass,hammer,heart,helmet,hook,horn,horse,hospital,iceberg,jail,kettle,knife,ladder,lemon,lock,magnet,mailbox,match,medal,mermaid,microphone,microscope,mirror,mushroom,nail,needle,necklace,newspaper,parachute,parrot,peanut,penguin,piano,pine tree,pineapple,pipe,pond,potato,prison,pumpkin,pyramid,rabbit,radio,ring,river,road,roof,sailboat,salt,saw,scales,scarf,scissors,scorpion,screw,seahorse,shark,sheep,shield,shoe,shovel,skeleton,skull,snail,snake,snowman,socks,sphinx,spider web,sponge,spoon,stairs,strawberry,submarine,suitcase,sunflower,swan,sword,syringe,table,tank,teapot,teddy bear,telephone,television,tent,thermometer,tie,tiger,toaster,toilet,tomato,toothbrush,toothpaste,tornado,tractor,traffic light,train,treasure,tree,triangle,truck,trumpet,turtle,umbrella,volcano,waffle,wagon,wall,wallet,watch,water,waterfall,watermelon,web,well,whale,wheel,whistle,windmill,window,wolf,worm,wrench,xylophone,yacht,zebra,zigzag,zipper,zombie,zoo";

const extraWords = [
    "accordion", "acorn", "alien", "alligator", "alpaca", "angel", "antelope", "anvil", "apron", "arch", "armadillo", "armor", "arrow", "asteroid", "avocado", "axe",
    "baboon", "badger", "bagel", "bagpipes", "bakery", "balcony", "ball", "ballet", "bamboo", "band-aid", "banjo", "bank", "barbecue", "barn", "barrel", "basketball", "bat", "bathroom", "bathtub", "battery", "beach", "beak", "bean", "beanie", "beavertail", "bed", "bee", "beef", "beetle", "bell", "belt", "bench", "berry", "bicycle", "bikini", "binoculars", "birdhouse", "biscuit", "blender", "blimp", "blizzard", "block", "blood", "blueberry", "board", "boat", "bomb", "bone", "bongo", "book", "bookmark", "bookcase", "boomerang", "boots", "bottle", "bow", "bowl", "bowling", "box", "boxing", "bracelet", "brain", "branch", "bread", "brick", "bridge", "broccoli", "broom", "brush", "bubble", "bucket", "buckle", "buffalo", "bulldog", "bullet", "bullseye", "bumper", "bun", "bunny", "burger", "bus", "bush", "butterfly", "button",
    "cabbage", "cabin", "cable", "cactus", "cake", "calculator", "calendar", "camel", "camera", "camp", "campfire", "can", "canal", "candy", "cane", "cannonball", "canoe", "cape", "car", "caramel", "cards", "carnival", "carpet", "carrot", "cart", "cartoon", "case", "cash", "cassette", "castle", "cat", "caterpillar", "cave", "ceiling", "celery", "cello", "centaur", "centipede", "chain", "chair", "chalk", "chameleon", "chandelier", "cheese", "cheetah", "chef", "cherry", "chess", "chest", "chestnut", "chicken", "chimney", "chipmunk", "chocolate", "chopsticks", "church", "cigar", "circle", "circus", "city", "clam", "clap", "claw", "clay", "cliff", "clip", "cloak", "clock", "cloth", "cloud", "clover", "clown", "club", "coach", "coal", "coast", "coat", "cobweb", "cocktail", "coconut", "coffee", "coin", "collar", "comb", "comet", "compass", "computer", "cone", "cookie", "copper", "coral", "corn", "corner", "cot", "cotton", "couch", "cough", "cow", "cowboy", "crab", "cracker", "crane", "crate", "crayon", "cream", "creek", "crib", "cricket", "crocodile", "cross", "crow", "crowd", "crown", "crumb", "crust", "crystal", "cube", "cuckoo", "cucumber", "cup", "cupcake", "curtain", "cushion", "cyclops", "cylinder",
    "dagger", "daisy", "dam", "dance", "dart", "date", "demon", "dentist", "desert", "desk", "detective", "devil", "diamond", "diary", "dice", "dinosaur", "diploma", "dirt", "disk", "dock", "doctor", "dog", "doghouse", "doll", "dollar", "dolphin", "dome", "donkey", "door", "doorknob", "dot", "dough", "doughnut", "dove", "dragon", "dragonfly", "drain", "drawer", "dress", "dresser", "drill", "drink", "drip", "drive", "drop", "drum", "duck", "dust", "dynamite",
    "eagle", "ear", "earmuffs", "earth", "earthquake", "easel", "eel", "egg", "eggplant", "elbow", "elephant", "elevator", "elf", "elk", "elm", "emu", "engine", "engineer", "envelope", "eraser", "escalator", "eye", "eyebrow", "eyelash", "eyepatch",
    "face", "factory", "fairy", "falcon", "fan", "fang", "farm", "farmer", "fat", "faucet", "feather", "fence", "fern", "ferret", "ferry", "fez", "field", "fig", "fighter", "file", "film", "fin", "finger", "fire", "fireball", "firefly", "fireman", "fireplace", "fish", "fishbowl", "fisherman", "fist", "flag", "flame", "flamingo", "flash", "flashlight", "flat", "flea", "fleece", "flesh", "flight", "flipper", "float", "flock", "flood", "floor", "flower", "fluff", "flute", "fly", "foal", "foam", "fog", "foil", "folder", "food", "foot", "football", "forest", "fork", "fort", "fossils", "fountain", "fox", "frame", "freckles", "freezer", "french fries", "fridge", "frog", "frost", "frosting", "frown", "fruit", "fudge", "fuel", "fur",
    "galaxy", "game", "garage", "garbage", "garden", "garlic", "gas", "gate", "gazelle", "gear", "gem", "genie", "ghost", "giant", "gift", "giraffe", "girl", "glass", "glasses", "globe", "glove", "glue", "gnoome", "goat", "goblin", "gold", "goldfish", "golf", "goose", "gorilla", "gown", "grape", "grapefruit", "grass", "grasshopper", "grave", "gravy", "greenhouse", "grenade", "grid", "grill", "grin", "ground", "group", "grove", "guard", "guitar", "gull", "gum", "gumball", "gun", "gym", "gymnast",
    "hair", "haircut", "hairdryer", "halibut", "hall", "halo", "ham", "hamburger", "hammer", "hammock", "hamster", "hand", "handcuffs", "handle", "hanger", "harp", "hat", "hatch", "hawk", "hay", "head", "headache", "headband", "headphones", "heart", "heat", "heater", "heaven", "hedge", "hedgehog", "heel", "helicopter", "helmet", "hen", "herd", "hermit", "hero", "hippo", "hive", "hockey", "hoe", "hole", "holiday", "home", "honey", "hood", "hoof", "hook", "horn", "horse", "hose", "hospital", "hot dog", "hotel", "hound", "hour", "house", "hubcap", "hug", "human", "hummingbird", "hump", "hurdle", "hurricane", "hut", "hyena", "hypnotize",
    "ice", "iceberg", "ice cream", "icicle", "idea", "igloo", "iguana", "illusion", "imp", "incense", "inch", "index", "infant", "ink", "inn", "insect", "instrument", "intern", "internet", "intestine", "invention", "iron", "island", "ivory", "ivy",
    "jack", "jacket", "jaguar", "jail", "jam", "jar", "jaw", "jay", "jazz", "jeans", "jeep", "jelly", "jellybean", "jellyfish", "jet", "jewel", "jigsaw", "job", "jockey", "jog", "joint", "joke", "journal", "judge", "jug", "juggler", "juice", "jump", "jumper", "jungle", "junk", "jury", "justice",
    "kangaroo", "karate", "kayak", "kebab", "keg", "kelp", "kennel", "ketchup", "kettle", "key", "keyboard", "khaki", "kick", "kid", "kidney", "king", "kiss", "kitchen", "kite", "kitten", "kiwi", "knee", "knife", "knight", "knit", "knob", "knot", "koala", "kraken",
    "label", "lace", "ladder", "ladle", "lady", "ladybug", "lake", "lamb", "lamp", "lane", "lantern", "lap", "laptop", "laser", "lasso", "latch", "laugh", "laundry", "lava", "lawn", "lawyer", "leaf", "leak", "leather", "leave", "leech", "leg", "lemon", "lemonade", "lemur", "lens", "leopard", "leprechaun", "letter", "lettuce", "level", "lever", "library", "lick", "lid", "life", "lift", "light", "bulb", "lighthouse", "lightning", "lily", "limb", "lime", "line", "link", "lion", "lip", "lipstick", "liquid", "list", "lizard", "llama", "loaf", "loan", "lobster", "lock", "locket", "locomotive", "log", "logo", "lollipop", "loop", "loot", "lord", "lotion", "love", "luggage", "lumberjack", "lunch", "lung", "lynx", "lyre",
    "macaroni", "macaw", "machine", "macho", "magazine", "magic", "magician", "magnet", "magnifying glass", "maid", "mail", "mailbox", "mailman", "makeup", "mall", "mammoth", "man", "manatee", "mango", "mansion", "map", "maraca", "marble", "march", "mare", "mark", "market", "marmot", "marshmallow", "mask", "mass", "mast", "match", "mate", "math", "matter", "mattress", "maze", "meat", "meatball", "mechanic", "medal", "medicine", "melon", "melt", "menu", "mermaid", "metal", "meteor", "meter", "microscope", "microwave", "midnight", "mile", "milk", "mill", "million", "mime", "mind", "mine", "miner", "mint", "mirror", "missile", "mitt", "mitten", "moat", "mob", "model", "mole", "mom", "money", "monitor", "monkey", "monster", "month", "monument", "moon", "moose", "mop", "morning", "mosquito", "moss", "moth", "mother", "motor", "motorcycle", "mountain", "mouse", "mousetrap", "mouth", "movie", "mower", "mud", "muffin", "mug", "mule", "mummy", "muscle", "museum", "mushroom", "music", "mustache", "mustard"
];

const finalWordsArray = Array.from(new Set([
    ...wordsString.split(',').map(w => w.trim()).filter(w => w.length > 0),
    ...extraWords
]));

module.exports = finalWordsArray;
